spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 2333
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  security:
    user:
      name: root
      password: 2333

